id: data_ingestion
namespace: dev
description: Fetch weather data from Open Meteo API, process the response, and upload the CSV to a bucket

inputs:
  - id: version
    type: STRING
    defaults: 0.1.0

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 23 * * *"  # Trigger every day at 23:00

tasks:
  - id: workingDirectory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Florent-COMPAGNONI/orchestration_ml.git
        branch: features/data_ingestion
      
      - id: fetchAuthToken
        type: io.kestra.plugin.gcp.auth.OauthAccessToken
        projectId: weather-forecast-427613
        serviceAccount: '{{ envs.gcp_sa_key }}'

  - id: run-script
    type: io.kestra.plugin.docker.Run
    containerImage: europe-west9-docker.pkg.dev/weather-forecast-427613/app/app_image:{{inputs.version}}
    commands:
      - python3 
      - /app/data_ingestion.py
    credentials:
      username: oauth2accesstoken
      password: "{{ outputs.fetchAuthToken.accessToken.tokenValue }}"
    outputFiles:
      - "weather_data_{{ now() | dateAdd(-2, 'DAYS') | date('YYYY_MM_dd') }}.csv"

  - id: upload_csv_to_bucket
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{ outputs['run-script'].outputFiles['weather_data_' + (now() | dateAdd(-2, 'DAYS') | date('YYYY_MM_dd')) + '.csv'] }}"

    to: "gs://easgi-iabd-weather-data/weather_data_{{ now() | dateAdd(-2, 'DAYS') | date('YYYY_MM_dd') }}.csv"
    serviceAccount: "{{ envs.gcp_sa_key }}"
