id: train-ml-model
namespace: esgi.iabd
description: Read training data, train model, upload model 

labels:
  env: dev
  project: weather-forecast

inputs:
  - id: file_name
    type: STRING
    defaults: "data_06_23_to_06_24.csv"

tasks:
  - id: downloadDataset
    type: "io.kestra.plugin.gcp.gcs.Download"
    from: "gs://easgi-iabd-weather-data/historical_data/{{ inputs.file_name }}"
    serviceAccount: "{{ envs.gcp_sa_key }}"
  
  - id: fetchAuthToken
    type: io.kestra.plugin.gcp.auth.OauthAccessToken
    projectId: weather-forecast-427613
    serviceAccount: '{{ envs.gcp_sa_key }}'

  - id: run-script
    type: "io.kestra.plugin.docker.Run"
    containerImage: europe-west9-docker.pkg.dev/weather-forecast-427613/app/app_image:0.0.1
    commands:
      - python3 
      - /app/train.py
      - "{{ outputs.downloadDataset.uri }}"
    credentials:
      username: oauth2accesstoken
      password: "{{ outputs.fetchAuthToken.accessToken.tokenValue }}"
    outputFiles:
      - "/app/lstm.keras"

  - id: upload
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{ outputs.run-script.outputFiles[0].uri }}"
    to: "gs://esgi-iabd-weather-models/lstm.keras"
